FROM python:2

# Set default work directory
WORKDIR /app

COPY g2f/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list                                                                                                                                                      0.7s
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list

COPY app.config ./
COPY g2f/g2f_DEGPlot.py ./
COPY g2f/g2f_expPlot.py ./
COPY g2f/GeneSet.py ./

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

ARG PGIDSCISTOR
ARG PGIDREF
ARG PGIDUSR

RUN groupadd --gid ${PGID} $USERNAME && \
    groupadd --gid ${PGIDSCISTOR} scistor_share_r && \
    groupadd --gid ${PGIDREF} reference_data_r && \
    groupadd --gid ${PGIDUSR} users_data_c && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME && \
    usermod -a -G scistor_share_r,reference_data_r,users_data_c $USERNAME

USER $USERNAME