FROM python:3

WORKDIR /app

COPY qtl_map/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base \
    # && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    --no-install-recommends build-essential r-base \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libarmadillo-dev \
    liblapack-dev \
    libblas-dev \
    gfortran \
    build-essential 

# RUN Rscript -e "install.packages(c('coloc', 'data.table', dplyr'))"

RUN R -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes"); remotes::install_github("chr1swallace/coloc@main")'

COPY app.config ./
COPY qtl_map/qtl_map_helpers.py ./qtl_map_helpers.py
COPY qtl_map/config_helpers.py ./config_helpers.py
COPY qtl_map/qtl_map.py ./qtl_map.py

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

ARG PGIDSCISTOR
ARG PGIDREF
ARG PGIDUSR

RUN groupadd --gid ${PGID} $USERNAME && \
    groupadd --gid ${PGIDSCISTOR} scistor_share_r && \
    groupadd --gid ${PGIDREF} reference_data_r && \
    groupadd --gid ${PGIDUSR} users_data_c && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME && \
    usermod -a -G scistor_share_r,reference_data_r,users_data_c $USERNAME

USER $USERNAME