FROM rocker/r-ver:4.3.2

ENV DEBIAN_FRONTEND=noninteractive

# System dependencies (R + Python)
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    build-essential \
    gfortran \
    libblas-dev \
    liblapack-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

# R packages
RUN R -e "install.packages(c('Rcpp','data.table','irlba','coloc', 'rprojroot', 'whereami', 'data.table', 'kimisc', 'R.utils', 'dplyr', 'argparse'), \
    repos='https://cloud.r-project.org', Ncpus=parallel::detectCores())"

# Python deps
WORKDIR /app
COPY xqtls/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["bash"]

COPY app.config ./
COPY ConfigParser.R ./
COPY xqtls/format_for_lava_coloc.py ./
COPY xqtls/run_coloc.R ./


# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

ARG PGIDSCISTOR
ARG PGIDREF
ARG PGIDUSR

RUN groupadd --gid ${PGID} $USERNAME && \
    groupadd --gid ${PGIDSCISTOR} scistor_share_r && \
    groupadd --gid ${PGIDREF} reference_data_r && \
    groupadd --gid ${PGIDUSR} users_data_c && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME && \
    usermod -a -G scistor_share_r,reference_data_r,users_data_c $USERNAME

USER $USERNAME