<option class="level2" value="sceQTL-singlebrain-Ast1">Ast1</option>
<option class="level2" value="sceQTL-singlebrain-OD">OD</option>
<option class="level2" value="sceQTL-singlebrain-OPC1">OPC1</option>
<option class="level2" value="sceQTL-singlebrain-OPC">OPC</option>
<option class="level2" value="sceQTL-singlebrain-OPC2">OPC2</option>
<option class="level2" value="sceQTL-singlebrain-IN3">IN3</option>
<option class="level2" value="sceQTL-singlebrain-Ast2">Ast2</option>
<option class="level2" value="sceQTL-singlebrain-Ext2">Ext2</option>
<option class="level2" value="sceQTL-singlebrain-Ast">Ast</option>
<option class="level2" value="sceQTL-singlebrain-Ast3">Ast3</option>
<option class="level2" value="sceQTL-singlebrain-Ext1">Ext1</option>
<option class="level2" value="sceQTL-singlebrain-Ast4">Ast4</option>
<option class="level2" value="sceQTL-singlebrain-Ext5">Ext5</option>
<option class="level2" value="sceQTL-singlebrain-Ext3">Ext3</option>
<option class="level2" value="sceQTL-singlebrain-Ext4">Ext4</option>
<option class="level2" value="sceQTL-singlebrain-End">End</option>
<option class="level2" value="sceQTL-singlebrain-IN1">IN1</option>
<option class="level2" value="sceQTL-singlebrain-IN5">IN5</option>
<option class="level2" value="sceQTL-singlebrain-Ext6">Ext6</option>
<option class="level2" value="sceQTL-singlebrain-Ext7">Ext7</option>
<option class="level2" value="sceQTL-singlebrain-IN4">IN4</option>
<option class="level2" value="sceQTL-singlebrain-Ext">Ext</option>
<option class="level2" value="sceQTL-singlebrain-IN">IN</option>
<option class="level2" value="sceQTL-singlebrain-Ext8">Ext8</option>
<option class="level2" value="sceQTL-singlebrain-IN6">IN6</option>
<option class="level2" value="sceQTL-singlebrain-MG3">MG3</option>
<option class="level2" value="sceQTL-singlebrain-IN7">IN7</option>
<option class="level2" value="sceQTL-singlebrain-IN2">IN2</option>
<option class="level2" value="sceQTL-singlebrain-OD1">OD1</option>
<option class="level2" value="sceQTL-singlebrain-OD2">OD2</option>
<option class="level2" value="sceQTL-singlebrain-MG">MG</option>
<option class="level2" value="sceQTL-singlebrain-MG4">MG4</option>
<option class="level2" value="sceQTL-singlebrain-MiGA3">MiGA3</option>
<option class="level2" value="sceQTL-singlebrain-MG1">MG1</option>
<option class="level2" value="sceQTL-singlebrain-MG2">MG2</option>
<option class="level2" value="sceQTL-singlebrain-OD3">OD3</option>