<option class="level1" value="null"> bryois2022Brain </option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_Microglia.txt.gz">Microglia</option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_Oligodendrocytes.txt.gz">Oligodendrocytes</option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_Pericytes.txt.gz">Pericytes</option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_OPCs.txt.gz">OPCs</option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_Excitatory.neurons.txt.gz">Excitatory.neurons</option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_Endothelial.cells.txt.gz">Endothelial.cells</option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_Inhibitory.neurons.txt.gz">Inhibitory.neurons</option>
<option class="level2" value="sceQTL/bryois2022Brain/sig_pairs/Brain_bryois2022Brain_Astrocytes.txt.gz">Astrocytes</option>
<option class="level1" value="null"> jerber2021Dopaminergic </option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D11.FPP.txt.gz">D11.FPP</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D30.FPP.txt.gz">D30.FPP</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D11.P_FPP.txt.gz">D11.P_FPP</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D30.DA.txt.gz">D30.DA</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D30.Epen1.txt.gz">D30.Epen1</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D30.Sert.txt.gz">D30.Sert</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.Astro.ROT_treated.txt.gz">D52.Astro.ROT_treated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.Astro.untreated.txt.gz">D52.Astro.untreated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.DA.ROT_treated.txt.gz">D52.DA.ROT_treated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.DA.untreated.txt.gz">D52.DA.untreated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.Epen1.ROT_treated.txt.gz">D52.Epen1.ROT_treated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.Epen1.untreated.txt.gz">D52.Epen1.untreated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.pseudobulk.untreated.txt.gz">D52.pseudobulk.untreated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.Sert.ROT_treated.txt.gz">D52.Sert.ROT_treated</option>
<option class="level2" value="sceQTL/jerber2021Dopaminergic/sig_pairs/Brain_jerber2021Dopaminergic_D52.Sert.untreated.txt.gz">D52.Sert.untreated</option>
<option class="level1" value="null"> singlebrain </option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ast.txt.gz">Ast</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ast1.txt.gz">Ast1</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ast2.txt.gz">Ast2</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ast3.txt.gz">Ast3</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ast4.txt.gz">Ast4</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_End.txt.gz">End</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext.txt.gz">Ext</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext1.txt.gz">Ext1</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext2.txt.gz">Ext2</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext3.txt.gz">Ext3</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext4.txt.gz">Ext4</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext5.txt.gz">Ext5</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext6.txt.gz">Ext6</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext7.txt.gz">Ext7</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_Ext8.txt.gz">Ext8</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN.txt.gz">IN</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN1.txt.gz">IN1</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN2.txt.gz">IN2</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN3.txt.gz">IN3</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN4.txt.gz">IN4</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN5.txt.gz">IN5</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN6.txt.gz">IN6</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_IN7.txt.gz">IN7</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_MG.txt.gz">MG</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_MG1.txt.gz">MG1</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_MG2.txt.gz">MG2</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_MG3.txt.gz">MG3</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_MG4.txt.gz">MG4</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_MiGA3.txt.gz">MiGA3</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_OD.txt.gz">OD</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_OD1.txt.gz">OD1</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_OD2.txt.gz">OD2</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_OD3.txt.gz">OD3</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_OPC.txt.gz">OPC</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_OPC1.txt.gz">OPC1</option>
<option class="level2" value="sceQTL/singlebrain/sig_pairs/Brain_singlebrain_OPC2.txt.gz">OPC2</option>
<option class="level1" value="null"> brainscope </option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Astro.txt.gz">Astro</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Chandelier__Pvalb.txt.gz">Chandelier__Pvalb</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_L5.6.NP.txt.gz">L5.6.NP</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_L4.IT.txt.gz">L4.IT</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_L2.3.IT.txt.gz">L2.3.IT</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_L6.CT.txt.gz">L6.CT</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_L6b.txt.gz">L6b</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_L5.IT.txt.gz">L5.IT</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Micro.PVM.txt.gz">Micro.PVM</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Lamp5.txt.gz">Lamp5</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Lamp5.Lhx6.txt.gz">Lamp5.Lhx6</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_L6.IT.txt.gz">L6.IT</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Sst__Sst.Chodl.txt.gz">Sst__Sst.Chodl</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_PC.txt.gz">PC</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_OPC.txt.gz">OPC</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Oligo.txt.gz">Oligo</option>
<option class="level2" value="sceQTL/brainscope/sig_pairs/Brain_brainscope_Vip.txt.gz">Vip</option>
