FROM python:3

WORKDIR /app

COPY Docker/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN apt update && apt install -y --no-install-recommends mysql-client \
    && rm -rf /var/lib/apt/lists/*

COPY transfer_dirs.py ./

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

ARG PGIDSCISTOR
ARG PGIDREF
ARG PGIDUSR

RUN groupadd --gid ${PGID} $USERNAME && \
    groupadd --gid ${PGIDSCISTOR} scistor_share_r && \
    groupadd --gid ${PGIDREF} reference_data_r && \
    groupadd --gid ${PGIDUSR} users_data_c && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME && \
    usermod -a -G scistor_share_r,reference_data_r,users_data_c $USERNAME

USER $USERNAME