FROM rocker/r-ver:4.3.2

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# ===============================
# System dependencies
# ===============================
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    build-essential \
    gfortran \
    libblas-dev \
    liblapack-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    bedtools \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Make python3 default
RUN ln -s /usr/bin/python3 /usr/bin/python

# ===============================
# R packages
# ===============================
RUN R -e "install.packages(c( \
    'Rcpp', 'data.table', 'dplyr', 'argparse', 'remotes', \
    'rprojroot', 'whereami', 'kimisc', 'R.utils' \
    ), repos='https://cloud.r-project.org', Ncpus=parallel::detectCores())"

# ===============================
# Python dependencies
# ===============================
WORKDIR /app

COPY flames/requirements.txt .
COPY flames/run_polyfun_FUMA.py ./

RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel && \
    pip3 install --no-cache-dir -r requirements.txt

# ===============================
# Install polyfun
# ===============================
RUN git clone https://github.com/omerwe/polyfun.git
ENV PYTHONPATH="/opt/polyfun:${PYTHONPATH}"

# ===============================
# Install FLAMES
# ===============================
RUN git clone https://github.com/Marijn-Schipper/FLAMES.git
ENV PYTHONPATH="/opt/FLAMES:${PYTHONPATH}"

# ===============================
# App workspace
# ===============================
WORKDIR /app
CMD ["bash"]

COPY app.config ./
COPY ConfigParser.R ./

# ===============================
# Non-root user setup
# ===============================
ARG USERNAME
ARG PUID
ARG PGID

ARG PGIDSCISTOR
ARG PGIDREF
ARG PGIDUSR

RUN groupadd --gid ${PGID} ${USERNAME} && \
    groupadd --gid ${PGIDSCISTOR} scistor_share_r && \
    groupadd --gid ${PGIDREF} reference_data_r && \
    groupadd --gid ${PGIDUSR} users_data_c && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} ${USERNAME} && \
    usermod -a -G scistor_share_r,reference_data_r,users_data_c ${USERNAME}

USER ${USERNAME}
