FROM r-base:4.2.3

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl unzip build-essential r-base \
    && curl https://vu.data.surfsara.nl/index.php/s/zkKbNeNOZAhFXZB/download -o magma_v1.10_static.zip\
    && unzip magma_v1.10_static.zip -d /usr/local/share/MAGMA \
    && chmod +x /usr/local/share/MAGMA/* \
    && rm magma_v1.10_static.zip \
    && rm -rf /var/lib/apt/lists/*
    
RUN Rscript -e "install.packages(c('rprojroot', 'whereami', 'data.table', 'kimisc'))"

COPY app.config ./
COPY magma_celltype/magma_celltype.R ./
COPY ConfigParser.R ./

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

ARG PGIDSCISTOR
ARG PGIDREF
ARG PGIDUSR

RUN groupadd --gid ${PGID} $USERNAME && \
    groupadd --gid ${PGIDSCISTOR} scistor_share_r && \
    groupadd --gid ${PGIDREF} reference_data_r && \
    groupadd --gid ${PGIDUSR} users_data_c && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME && \
    usermod -a -G scistor_share_r,reference_data_r,users_data_c $USERNAME

USER $USERNAME